version: '3.8'

services:
  food-data-processor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data  # Persist downloaded files locally
      - ./keys/my-creds.json:/app/gcs-key.json:ro  # Mount GCS key (remove if not needed)
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcs-key.json  # Optional, for GCS auth